spring.application.name=demo

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/HW6
spring.datasource.username=root
spring.datasource.password=Anam92raza
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Configuration

jwt.secret.key = w3e34xuT6os0rEXtSSSiESXYj5xn7kCLR3JXMXa8YCcb7Zgs=
jwt.access.expiration=1800000 
#30 minutes
jwt.refresh.expiration=5184000000
#1 month

spring.devtools.restart.enabled=true


free.allowed = 1
basic.allowed = 2
premium.allowed = 4

